### ISSUE TITLE
MQTTnet.EventBus.AspNetCoreApi_Integration - Exception-Userunhandled

### ISSUE THREAD

**Issue by malidebeli** [Revalcon/MQTTnet.EventBus#36]
When i try to run web app MQTTnet.EventBus.AspNetCoreApi_Integration
i got this error
"System.InvalidOperationException: 'Unable to resolve service for type 'MQTTnet.EventBus.IEventProvider' while attempting to activate 'MQTTnet.EventBus.Impl.MqttEventBus'.'"

Stack trace:
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.<>c__DisplayClass7_0.<GetCallSite>b__0(Type type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at MQTTnet.EventBus.AspNetCoreApi_Integration.ApplicationBuilderExtansions.UseEventBus(IApplicationBuilder app, Action`1 action) in F:\Vjezbanje informatike\MQTTnet.EventBus-master\samples\MQTTnet.EventBus.AspNetCoreApi_Integration\Startup.cs:line 79
   at MQTTnet.EventBus.AspNetCoreApi_Integration.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in F:\Vjezbanje informatike\MQTTnet.EventBus-master\samples\MQTTnet.EventBus.AspNetCoreApi_Integration\Startup.cs:line 68
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)

**Comment by arttonoyan** [comment]
Hi @malidebeli 
This example is outdated, I didn't have time to update it.
[This example](https://github.com/Revalcon/MQTTnet.EventBus/blob/master/samples/MQTTnet.EventBus.ConfigurationApp/Program.cs) is the best for testing, you can try it and in the future, if you have problems configuring it in ASP.NET I will help.
I haven't managed to write the documentation yet.

**Comment by arttonoyan** [comment]
@malidebeli I want to close this issue, do you have any questions or can I help you with something?
